### ISSUE TITLE
Paar zaken verdwenen in nieuwe versie

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#10]
Of ik kijk verkeerd of het is bij mij verdwenen.

De Header is verdwenen
De sliders bij de schakelaars. (Error in debug: Notice: Undefined index: status in hw/index.php on line 84}
Het door klikken naar history van de sensoren en temperatuur. (de rest heb ik niet) 
Het door klikken naar de settings pagina

**Comment by Egregius** [comment]
De header is niet langer nodig. Alles is bedienbaar via de blokken. 
Zie oa https://github.com/Egregius/HomewizardPHP/wiki/Versie-historiek
Als je kijkt bij 'bewerk schakelaars' heb je dan geen 'gaten' in de id's? Anders heb je last van deze bug https://github.com/Egregius/HomewizardPHP/issues/3

**Comment by Egregius** [comment]
Issue #3 opgelost in v20150110
