### ISSUE TITLE
timezone & database foutmelding

### ISSUE THREAD

**Issue by Hendrik83** [Egregius/HomewizardPHP#11]
Met HomewizardPHP krijg ik helaas onderstaande foutmeldingen.

In de footer en overal als ik de 2e melding handmatig oplos.

`It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in <b>/usr/local/www/apache24/data/homewizard/history.php</b> on line 43`

Met het updaten van de schakelaars:

`0-Woonkamer: switch<br/>There was an error running the query [INSERT INTO switches (`id_switch`, `name`, `type`, `favorite`) values (0, 'Woonkamer', 'switch', 'no') ON DUPLICATE KEY UPDATE `name`='Woonkamer', `type`= 'switch', `favorite`= 'no'] > [Field 'volgorde' doesn't have a default value`

Apache/2.4.10 (FreeBSD) PHP/5.6.3

**Comment by Egregius** [comment]
Kan je deze query in de database uitvoeren? 
ALTER TABLE `switches` CHANGE `volgorde` `volgorde` SMALLINT(6) NOT NULL DEFAULT '0';
Die zorgt ervoor dat het veld volgorde standaard op 0 gezet wordt. 

Voor de tijdzone ga ik meteen eens onderzoeken

**Comment by Egregius** [comment]
Kan je bij lijn 8 van header.php eens dubbele / zetten? 
//putenv( "PHP_TZ=Europe/Amterdam" );

**Comment by Hendrik83** [comment]
De database foutmelding lost zich zo op inderdaad.
Helaas blijft de fout over de tijdzone bestaan.

![Image](http://h.imgurl.nl/m)

**Comment by Egregius** [comment]
Kan je eens proberen met de nieuwe header.php? 
Blijkbaar heb je geen default time zone settings in php.ini staan.

**Comment by Hendrik83** [comment]
Zou kunnen is gewoon een standaard lamp installatie.

Maar het werkt nu wel! 

Thx

**Comment by Egregius** [comment]
Toppie :)

**Comment by Hendrik83** [comment]
Moet weer even open..

Timezone foutmelding is er nog in history_to_sql.php

**Comment by Egregius** [comment]
Fixed in een update voor history_to_sql.php

**Comment by Hendrik83** [comment]
Ok we zijn onderweg.  :+1: 

Tijdens het updaten.
![](https://copy.com/MkayI2a0wFbL/UAJD.png)

Ik kwam toevallig achter het volgende toen ik uitgelogd was.

![](https://copy.com/9HIKqWeCcxl0/Wb0J.png)
