### ISSUE TITLE
Button te klein

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#12]
De button "Update schakelaars, sensoren, historiek" lijkt te klein. De tekst word tot "Update schakelaars, sensoren, his" staat op de button

**Comment by Egregius** [comment]
Os? browser? Device?

**Comment by DrakeNL** [comment]
android, standard brouwser, Galaxy S3
Windows 8.1. IE / Firefox, laptop

**Comment by Egregius** [comment]
IE is sowieso een *** browser, doet altijd wel over iets moeilijk. 
Maar, de knoppen zijn breder met de nieuwe css.
