### ISSUE TITLE
Verberg Schakelaars enz

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#13]
is het misschien een idee om optie per schakelaar, scene, enz mee te geven zodat je een schakeling kunt verbergen. natuurlijk wel mer een "More" optie zodat je alle schakelingen zichtbaar krijgt

**Comment by Egregius** [comment]
Dat staat op de roadmap om ooit te doen. 
Ik zou daarvoor de favoriten van de HW app gebruiken, die info staat toch al in de database.

**Comment by Egregius** [comment]
Hmmm, de truc die ik had voor detail scenes optional doet het niet. De hele tabel gaat naar de vaantjes erdoor. 
Heb je dan zoveel schakelaars? 
Is de optie volgorde niet voldoende?

**Comment by DrakeNL** [comment]
Ik heb op dit moment nog maar 5 schakelingen, maar zat te denken aan de toekomst als er een tablet aan de muur hang en je de vaak gebruikte schakelingen direct kunt aanroepen zonder al te veel scrollen

**Comment by Egregius** [comment]
De minder gebruikte kan je in bewerk schakelaars een hoger getal geven bij volgorde. 
Maar, via een omweg (refresh page) lukt het perfect. Komt er dus binnenkort aan.

**Comment by Egregius** [comment]
Beschikbaar voor schakelaars in v20150111.

**Comment by DrakeNL** [comment]
optie werkt bij de schakelingen van het type switch/dimmer. Werkt nog niet bij het type Somfy

**Comment by Egregius** [comment]
I know :p

**Comment by Egregius** [comment]
Favorieten voor Somfy toegevoegd in v20150128
