### ISSUE TITLE
temperatuursensor id nummer issue

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#14]
herradelijk handmatig history_to_sql.php uitgevoerd. Echter geen data in database.

Bij uitvoeren met de Debug aan onderstaande error bij de tempratuur

Notice: Undefined index: response in /history_to_sql.php on line 102 Warning: Invalid argument supplied for foreach() in /history_to_sql.php on line 102 

  $json = file_get_contents($jsonurl.'te/graph/1/day');  veranderd naar   $json = file_get_contents($jsonurl.'te/graph/0/day'); heeft het opgelost

Ik heb (nog) maar 1 temeratuur meter

**Comment by Egregius** [comment]
OK, gaan we bekijken. Mijn thermometer heeft meteen ID1 gekregen.
Zal er een parameter van maken. Naar mijn mening is het toch enkel de buitensensor die moet bewaard worden, ook al heb je er meerdere binnen.

**Comment by Egregius** [comment]
Should be fixed in v20150111.
Toch meerdere thermometers etc importeren ;)

**Comment by DrakeNL** [comment]
bij uitvoeren van de history_to_sql.php de onderstaande error

Importing Temperature
2015-01-10 00:10 - 16,5 - 57
There was an error running the query [INSERT IGNORE INTO temperature (`timestamp`, `te`, `hu`, `id_sensor`) values ('2015-01-10 00:10', '16,5', '57', '0') ] > [Unknown column 'id_sensor' in 'field list']

zie wel dat de Create database is aangepast ik heb de database (nog) niet opnieuw gecreerd

**Comment by Egregius** [comment]
Hoeft niet. 
Via settings - update database zou dat automatisch moeten verlopen.

**Comment by DrakeNL** [comment]
bij uitvoeren van de update database onderstaande error.

There was an error running the query [ALTER TABLE `temperature` ADD `id_sensor` INT DEFAULT NULL ;ALTER TABLE `temperature` DROP PRIMARY KEY; ALTER TABLE `temperature` ADD PRIMARY KEY (`timestamp`,`id_sensor`);][You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ALTER TABLE `temperature` DROP PRIMARY KEY; ALTER TABLE `temperature` ADD PRIMAR' at line 1]

**Comment by Egregius** [comment]
Ik heb de query's eens opgesplitst ipv 3 in 1 commando. 
In phpmyadmin mag dat, blijkbaar niet via php.
