### ISSUE TITLE
Error bij importing Wind

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#15]
krijg met uitvoeren /history_to_sql.php de onderstaande error.

Ik heb op dit moment geen wind meter aangesloten. maar heb een vermoeden dat het in de 2 van de "$json = file_get_contents($jsonurl.'wi/graph/2/day');" zit

Importing Wind
 Notice: Undefined index: response in /history_to_sql.php on line 170 Warning: Invalid argument supplied for foreach() in /history_to_sql.php on line 170

**Comment by Egregius** [comment]
Should be fixed in v20150111.
