### ISSUE TITLE
Error on updating sensors and devices

### ISSUE THREAD

**Issue by Martinvdm** [Egregius/HomewizardPHP#19]
Importing Temperature
2015-01-11 00:10 - 52 - 75
There was an error running the query [INSERT INTO temperature (`timestamp`, `te`, `hu`, `id_sensor`) values ('2015-01-11 00:10', '52', '75', '0') ON DUPLICATE KEY UPDATE `te`='52', `hu`='75'] > [Unknown column 'id_sensor' in 'field list']

**Comment by Egregius** [comment]
Altijd update database (via settings) doen bij een nieuwe versie ;)

**Comment by Martinvdm** [comment]
Is een verse installatie.
Ik stuur je zo nog een PM via Tweakers met een aantal dingen.

Of kan ik je ook mailen?

Groet

Martin

Van: Guy Verschuere [mailto:notifications@github.com]
Verzonden: maandag 12 januari 2015 20:14
Aan: Egregius/HomewizardPHP
CC: Martin van der Meer
Onderwerp: Re: [HomewizardPHP] Error on updating sensors and devices (#19)


Altijd update database (via settings) doen bij een nieuwe versie ;)

**Comment by Egregius** [comment]
Het create database script is ouder. Via settings kan je update database doen, die zal de database aanpassen naar de laatste versie.
