### ISSUE TITLE
Somfy toevoegen

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#2]
De SQL query heb ik aangepast naar --> $sql="select id_switch, type, volgorde from switches where type like 'switch' OR type like 'dimmer' OR type like 'somfy' order by volgorde asc, favorite desc, name asc";

 Hij vind nu ook netjes de Somfy switches. Hierna het if($row['type']=='switch') stuk uitgebreid naar if($row['type']=='switch' or 'somfy') {

 Ik krijg netjes de schakelaars er bij te zien ik krijg alleen niet de labels te zien.

**Comment by DrakeNL** [comment]
bij debug krijg ik 

on line 68 Notice: Undefined offset: 44 in /index.php on line 70

**Comment by Egregius** [comment]
Er komt geen status terug van een somfy. Dit betekent dat deze op een andere manier moeten opgevraagd worden, net als de scenes dus. 
We gaan moeten zoeken met welke url de somfy's opgevraagd kunnen worden.

**Comment by Egregius** [comment]
De commando's verkregen via Tweakers, er is geen status beschikbaar. 
Ik implementeer dit wellicht vandaag nog. 
/<HW PASSWORD>/sf/0/down
/<HW PASSWORD>/sf/0/up
/<HW PASSWORD>/sf/0/stop

**Comment by Egregius** [comment]
Opgelost in v20150109 ;)
