### ISSUE TITLE
Scene wordt niet meer weergegeven

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#21]
Na de update naar 20150116 worden mijn scene niet getoond

**Comment by Egregius** [comment]
Klopt, dit komt omdat ik nu get-status gebruik ipv get-sensors. 
Bedoeling is om ook de scenes in de database te gooien, is uiteindelijk toch nodig om ze te kunnen verbergen.

**Comment by Egregius** [comment]
Ik heb voorlopig een andere index.php gezet zodat scenes terug werken, in afwachting dat het helemaal in de database steekt.

**Comment by Egregius** [comment]
Scenes in database in favorieten mogelijk.
