### ISSUE TITLE
function.php

### ISSUE THREAD

**Issue by DavidVM1982** [Egregius/HomewizardPHP#24]
beste,

ik krijg de volgende melding
op elke pagina
Warning: include(functions.php): failed to open stream: No such file or directory in /volume1/web/Mechelen/hwtest/header.php on line 7

Warning: include(): Failed opening 'functions.php' for inclusion (include_path='.:/var/packages/PEAR/target') in /volume1/web/Mechelen/hwtest/header.php on line 7

De file zit niet mee in de upload.

mvg 
David

**Comment by Egregius** [comment]
Oeps...
Net header.php opnieuw geladen. 
Functions is op heden toch nog leeg.

**Comment by DavidVM1982** [comment]
geen probleem,
zier de regel er zelf wel uit.

zelf ben ik ook zo iets aan het ontwikkelen. maar ben grafische nog niet zo sterk.
de bedoeling is voor mij om en & of functie  toe te voegen aan de homewizard als ook een log boek
logboek  & de en functie werkt al. Moet het alleen nog wat gebruiksvriendelijk er maken

**Comment by Egregius** [comment]
Check even actionscron.php dan ;)
Een eerste versie van conditioneel schakelen. 
Ben er nog niet uit hoe ik het in een grafische interface moet gieten en of ik dat wel wil doen. Hardcoded is misschien moeilijker aan te passen maar heb je wel echt absolute vrijheid in de EN/OF contstructies.

**Comment by Egregius** [comment]
O ja, misschien kan je de rep forken en kunnen we samenwerken?

**Comment by DavidVM1982** [comment]
ben er vooral geen expert in php en dergelijke.

heb de file gelezen want zelf heb ik nog geen weerstation/brander/energie op mijn HW aangesloten


had het zelfde idee te doen als op http://reinald.homeip.net/
maar dan geen scenes te gebruiken voor de voorwaarden en de acties.

de en functie werkt. en wou deze week het in een grafische vorm gieten maar wegens tijds gebrek is dit nog niet gelukt.

ik zal mijn projectje is opschonen en dan delen.
dan kunnen we kijken wat we kunnen samenvoegen

David

**Comment by Egregius** [comment]
Ik ga mijn acties verder delen in de toekomst. Met een beetje knippen en plakken zijn die best begrijpbaar.
