### ISSUE TITLE
2 keer een sensor met ID 0

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#25]
Doordat op dit moment de tempsensor kunt bewerken op de bewerk sensors heb ik nu 2 keer een sensor met ID 0 in mijn database

Hierdoor als ik 1 van de 2 aanpas wordt de ander ook aangepast

output van de JSON get-sensor
"kakusensors": 
[{"id":0,"name":"12 deur achter","status":"no","type":"contact","favorite":"no","timestamp":"20:13","cameraid":null},{"id":1,"name":"21 Keuken","status":null,"type":"smoke","favorite":"no","timestamp":"00:00","cameraid":null}]

"thermometers":[{"id":0,"name":"Kinderkamer","channel":1,"model":0,"te":16.9,"hu":51,"te+":19.5,"te+t":"17:49","te-":15.8,"te-t":"02:49","hu+":53,"hu+t":"02:29","hu-":49,"hu-t":"18:08","outside":"yes","favorite":"no"}]

**Comment by Egregius** [comment]
Vormt dit dan een probleem?

Verstuurd vanaf mijn iPhone

**Comment by DrakeNL** [comment]
Ze kunnen nu niet separaat van elkaar gehide of geshowd worden.

Ik weet niet of er in de toekomst meer dubbele tussen komen en dus meer "probleem" gevallen

**Comment by Egregius** [comment]
Ja, ik bedacht het gisteren nog. Ik doe update where id = 
Heb daar nu ook type in opgenomen en daarmee is het gefixed.
