### ISSUE TITLE
layout niet goed

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#26]
Wanneer er geen favorieten zijn in het sensor blok staat:
De footer direct onder de header (dus achter de blokken)
Wind en regen blok staan rechts buiten veld

Zodra er op de sensoren blok geklikt wordt op de sensoren zichtbaar te maken, wordt alles netjes naast en onder elkaar geallignd

**Comment by Egregius** [comment]
Wellicht ergens een error die verschijnt. 
'k Moet eens meer aandacht geven aan de error weergaves. 
Ergens wel de bedoeling dat er van elk type minstens 1 favoriet is.

**Comment by Egregius** [comment]
Ah, der stond nog een /div op de verkeerde plaats. 
Should be fixed in 20150129

**Comment by Egregius** [comment]
In de huidige versie 20150129 steekt de mogelijkheid om blokken te tonen/verbergen. 
Ik ga later mogelijk maken om op die manier alle sensors etc als niet favoriet te zetten zodat ze enkel getoond worden als er op de titel geklikt wordt. 
Door dan toon_* op UIT te zetten kan het blok volledig verborgen worden. Bv indien geen Somfy etc.

**Comment by DrakeNL** [comment]
Er worden nu 2 blokken samen gevoegd in de Scenes blok. Ik vermoed dat de "echo '</tbody></table>';" op regel 241 verkeerd staat

**Comment by Egregius** [comment]
Probeer even de nieuwe index. De tabel werdt een } te vroeg gesloten indien detail scene optional of yes.

**Comment by DrakeNL** [comment]
Dit loste het op
