### ISSUE TITLE
meerdere blokken verdwijnen

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#27]
Als ik alle schakelaars verberg door ze als niet favorite zet dan wordt ook het Scenes blok verborgen en andersom

**Comment by Egregius** [comment]
Wellicht hetzelfde ID probleem geweest.

**Comment by DrakeNL** [comment]
Lijkt het nu wel goed te doen.

Enige is dat als ik alle toon_* op aan zet de alle blokken waar ik niets van heb niet getoond worden (wat ook goed is) behalve de radiatoren. Die komt toch op het scherm ondanks dat ik geen kranen heb.

**Comment by Egregius** [comment]
Het is enkel regen, wind en energylink die niet getoond worden als er geen zijn. Van al de rest moet je op z'n minst een blok met de titel hebben als je toon_ op aan zet. 
Maar waarom zet je hem op aan als je geen hebt? :p
