### ISSUE TITLE
temp word niet weergegeven

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#28]
mijn tempratuur wordt niet meer weergegeven in het Tempratuurblok op de Index
krijg onderstaande error
Notice: Undefined index: te in /.../index.php on line 121 Notice: Undefined index: hu in /.../index.php on line 122 

ook op de temp pagina wordt de tempratuur niet meer bovenin weergegeven.
krijg onderstaande error:
Notice: Undefined index: te in /.../temp.php on line 28 Notice: Undefined index: hu in /.../temp.php on line 28

**Comment by Egregius** [comment]
Zijn je thermometers al geimporteerd als sensors?

**Comment by DrakeNL** [comment]
Ik vermoed dat het een lege batterij is. nieuwe temp sensor (wilde er toch nog 1 bij hebben) doet het wel goed. Zal morgen eens kijken naar andere batterijen
