### ISSUE TITLE
Scenes blok klapt niet meer uit

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#29]
Het klikken op de titel zorgt er niet voor dat alle Scenes worden weergegeven.
onderstaande warning staat in het blok
Warning: mysqli_result::fetch_assoc(): Couldn't fetch mysqli_result in /.../index.php on line 216

**Comment by Egregius** [comment]
Probeer eens met de nieuwe index.php

**Comment by DrakeNL** [comment]
Dat loste het op
