### ISSUE TITLE
Temperatuur geschiedenis geeft verkeerde waarden

### ISSUE THREAD

**Issue by jhore** [Egregius/HomewizardPHP#30]
de nieuwe index.php van vandaag loste het scenes probleem bij mij op, Maar als ik doorklik op de temperatuur meters krijg ik vreemde waarden. Zie screenshot. Prachtig werk voor de rest.
![schermafbeelding 2015-01-30 om 14 53 14](https://cloud.githubusercontent.com/assets/10773695/5976572/cb5027bc-a88f-11e4-9cb2-cb2966682763.png)

**Comment by Egregius** [comment]
Huh? 
Welke waardes staan er dan in de tabel?

**Comment by jhore** [comment]
Hoi Guy,

als ik ze importeer krijg je het volgende:

Importing Temperature
2015-01-29 13:15 - 38 - 70
2015-01-29 13:30 - 38 - 70
2015-01-29 13:45 - 4 - 69

Er staat in dit geval geen punt tussen de temperatuur waardes. 

b.v: 

2015-01-29 13:15 - 38 - 70 moet zijn 3.8
2015-01-29 13:30 - 38 - 70 moet zijn 3.8
2015-01-29 13:45 - 4 - 69 moet zijn 4.0

en:

2015-01-30 20:40 - 1 - 89 moet zijn 1,0
2015-01-30 20:55 - 09 - 90 moet zijn 0,9
2015-01-30 21:10 - 09 - 90 moet zijn 0,9
2015-01-30 21:25 - 09 - 91 moet zijn 0,9
2015-01-30 21:40 - 1 - 91 moet zijn 1,0
2015-01-30 21:52 - 13 - 91 moet zijn 1,3

Hierdoor gaan de maximale en minimale dagtemperaturen ook rare waardens aangeven.

Tevens krijg ik meegestuurde fout bij het instellen van een radiator thermostaat die stuur ik mee in een screenshot. De waarde word wel in de thermostaatkraan gezet overigens.
 

Vr gr,

John Horeman





-----Oorspronkelijk bericht-----
Van: Guy Verschuere [mailto:notifications@github.com]
Verzonden: vr 30-1-2015 17:38
Aan: Egregius/HomewizardPHP
CC: John Horeman
Onderwerp: Re: [HomewizardPHP] Temperatuur geschiedenis geeft verkeerde waarden (#30)
 
Huh? 
Welke waardes staan er dan in de tabel? 

---
Reply to this email directly or view it on GitHub:
https://github.com/Egregius/HomewizardPHP/issues/30#issuecomment-72229579=

**Comment by DrakeNL** [comment]
Bij mij geeft hij netjes de juiste waardes aan. Heeft het misschien iets te maken met landen instellingen>

**Comment by Egregius** [comment]
Ik zou ook denken aan landinstellingen, maar waar? 
Import zou dit moeten geven:
Importing Temperature
2015-01-30 00:10 - 0.7 - 90
2015-01-30 00:25 - 0.7 - 90
En de temp historiek:
Laatste uur
Tijd	Temp	Rel Voch
za 31 jan 08:00  	 -1.2 °C  	 94 % 
za 31 jan 07:00  	 -1.1 °C  	 93 % 
za 31 jan 06:00  	 -0.9 °C  	 93 % 
za 31 jan 05:00  	 -0.5 °C  	 93 % 

bij jou staat de datum in het Engels. 
Kan er in settings zijn in php.ini die blokkeert dat deze twee gebruikt worden? 
 setlocale(LC_ALL,'nl_NL.UTF-8');
date_default_timezone_set('Europe/Brussels')

En welke versie van php heb je draaien?

**Comment by jhore** [comment]
PHP versie: 	5.2.9-2 

uit de php.ini:

date/time support 	enabled
"Olson" Timezone Database Version 	2009.1
Timezone Database 	internal
Default timezone 	Europe/Paris

Directive	Local Value	Master Value
date.default_latitude	31.7667	31.7667
date.default_longitude	35.2333	35.2333
date.sunrise_zenith	90.583333	90.583333
date.sunset_zenith	90.583333	90.583333
date.timezone	no value	no value

**Comment by jhore** [comment]
Al gevonden wat het probleem is denk ik. Ik draai dit op een windows machine. Hier is het setlocale anders. nadat ik in de temp.php onder header include de onderstaande regel had gezet kreeg ik de nederlandse output.

setlocale(LC_ALL, 'nld_nld');

Moest alleen nog een %d in de data output erbij zetten om de dag nummer te krijgen:

<td>'.strftime("%a %d %e %b %H:%M",strtotime($row['timestamp'])).'&nbsp;</td>

Volgens mij kan ik hem gewoon in de header erbij zetten onder de setlocale(LC_ALL,'nl_NL.UTF-8');

**Comment by Egregius** [comment]
Bij werkt het alleszins als ik het zo in header.php zet:
setlocale(LC_ALL,'nl_NL.UTF-8');
setlocale(LC_ALL, 'nld_nld');

Indien het niet werkt maak ik er wel een parameter van zodat je niet bij elke nieuwe versie de aanpassing moet doen.

**Comment by jhore** [comment]
Zoals het er nu uit ziet is dat voldoende. Moet alleen nog de %d er tussen zetten om de dag nummer te krijgen. Heb nog wat kleine andere issue'. zal daar wel een aparte melding van maken
