### ISSUE TITLE
Virtuele schakelaars (ip switch) schakelen alleen aan, niet uit.

### ISSUE THREAD

**Issue by jhore** [Egregius/HomewizardPHP#31]
Ik gebruik de nieuwe ip switchen. De volgende code gebruik ik daarvoor:

Aanzetten: http://<ipnummer>:<poort>/api/actions.html?option=SwitchOn&id=1
Uitzetten: http://<ipnummer>:<poort>/api/actions.html?option=SwitchOff&id=1

Het aanzetten gaat goed, maar uitzetten werkt niet, de switch blijft niet op aan staan, maar springt weer naar de begin stand. Zodoende kan ik niet uitzetten, alleen aanzetten

**Comment by Egregius** [comment]
Dat wist ik :p 
Opgelost in de index.php van vandaag. 
Wel met on/off buttons want je krijgt daar geen status van en gaan we ook nooit krijgen volgens HW support.

**Comment by jhore** [comment]
buttons zijn er inerdaad, klein foutje in de index.php geslopen:

regel 33: 	if($group != $row['volgorde']) $tdstyle = 'style="'.$css_td_newgroup.'"';
moet denk ik zijn:
if($group != $row['volgorde']) $tdstyle = 'style="border-top:1px solid black; padding-top:10px;"';

tevens geven de radiatoren met deze index.php de volgende fout:

There was an error running the query [Unknown column 'temp' in 'field list']
Notice: Trying to get property of non-object in E:\websites\Homewizard\index.php on line 171

Fatal error: Call to a member function free() on a non-object in E:\websites\Homewizard\index.php on line 215

**Comment by Egregius** [comment]
Die css is geen foutje hoor. Wellicht nog update.php niet aangepast. Nogal veel bijgezet vandaag.

**Comment by Egregius** [comment]
A nee, toch niet. 
Staat wel al in update.php:
	if($versie<20150131) {
$sql="ALTER TABLE `switches` ADD `temp` SMALLINT NULL ;";
if(!$result = $db->query($sql)){ echo ('There was an error running the query ['.$sql.'][' . $db->error . ']');}
$sql="insert into versie (versie) VALUES ('20150131');";
if(!$result = $db->query($sql)){ die('There was an error running the query ['.$sql.'][' . $db->error . ']');}
}
if($versie<20150201) {
$sql="INSERT IGNORE INTO `settings` (`variable`, `value`) VALUES ('css_td_newgroup', 'border-top:1px solid black; padding-top:10px;')";
if(!$result = $db->query($sql)){ echo ('There was an error running the query ['.$sql.'][' . $db->error . ']');}
$sql="insert into versie (versie) VALUES ('20150201');";
if(!$result = $db->query($sql)){ die('There was an error running the query ['.$sql.'][' . $db->error . ']');}
}

Denk eraan om telkens de versie historiek te lezen hier in de wiki en om na een update van de files steeds naar settings>update database te gaan.

**Comment by jhore** [comment]
Je hebt gelijk, was geen fout, maar een vergeten udate database door mijn dommigheid. Nu alles helemaal in orde.
