### ISSUE TITLE
Optie om temperatuur aan radiator te hangen

### ISSUE THREAD

**Issue by jhore** [Egregius/HomewizardPHP#32]
Deze werkt prima, alleen niet voor ID 0.

Deze regel zorgt daar voor: 
if($row['temp']>0) {

Heb hem op -1 gezet en dan kan ik ook temp id 0 gebruiken.

**Comment by Egregius** [comment]
Opgelost met if(!empty($row['temp'])) { in v20150204.

**Comment by jhore** [comment]
Nu pas tijd gehad om te testen, maar laat bij mij nog steeds niets zien.

**Comment by Egregius** [comment]
Kan je nog eens proberen met v20150207? 
Heb nu: if(!empty($row['temp']) || $row['temp']==0) {
Hopelijk geeft dat nu niet elders problemen :p

**Comment by jhore** [comment]
Ik heb deze regel gestest voorat ik geupgrade had naar 20150207 door de regel te kopieeren en dit werkt zonder bijwerkingen zoals ik nu kan zien.

**Comment by jhore** [comment]
helaas geeft een NULL field bij mij nog altijd fout meldingen. Heb de regel weer naar: if($row['temp']>-1) { gezet.

**Comment by Egregius** [comment]
Omdat er dan null staat bij die kraan? 
Wat als je daarin -1 zet?

**Comment by jhore** [comment]
dan laat hij niets achter de insteltemperatuur zien. Dus nog steeds ok. Wel krijg ik de volgende melding op het moment dat ik de temperatuur veranderd:

Warning: Missing argument 4 for radiator(), called in E:\websites\Homewizard\index.php on line 10 and defined in E:\websites\Homewizard\functions.php on line 86

Warning: Missing argument 5 for radiator(), called in E:\websites\Homewizard\index.php on line 10 and defined in E:\websites\Homewizard\functions.php on line 86

Notice: Undefined variable: reply in E:\websites\Homewizard\functions.php on line 112

(hij veranderd de temperatuur wel op de radiatorkraan)

**Comment by jhore** [comment]
Aanvulling dit doet hij nu bij elke schakeling, en heeft met de volgende variabelen te maken:

$notify $failonly en $reply

**Comment by Egregius** [comment]
Heb jij debug steeds op ja staan? 
Anyway, opgelost in v20150208. (de missing argument althans).
Dat van de temperatuurid blijf ik maar iets raars vinden.

**Comment by jhore** [comment]
Nee debug staat uit. maar eigenlijk is het probleem al opgelost met if($row['temp']>-1) {  en heb ik geen bijwerkingen.

**Comment by Egregius** [comment]
Dan heb jij ergens in php.ini staan om alle fouten te tonen. Zou je moeten uitschakelen omdat dat een mogelijks security issue kan zijn. 
Door debug op AAN te zetten worden die dan tijdelijk geactiveerd:
error_reporting(E_ALL);ini_set("display_errors", "on");

'k Vind het toch jammer dat ik het issue niet kan simuleren en een oplossing bieden. Nu ga je bij elke update er moeten aan denken dat je dat moet aanpassen.

**Comment by jhore** [comment]
Je had gelijk wat betreft mijn php.ini. Ivm security issue deze gelijk in de php.ini op off gezet.

**Comment by jhore** [comment]
overigens is het voor mij nu ok, heb id 0 temperatuur sensor omgewisseld met de buiten temperatuur. Dus geen probleem voor mij meer.

**Comment by Egregius** [comment]
Top :)
