### ISSUE TITLE
Foutmelding met laatste updates

### ISSUE THREAD

**Issue by jhore** [Egregius/HomewizardPHP#33]
Notice: Undefined variable: temp_correctie0 in E:\websites\Homewizard\data.php on line 41

Database geupdate maar melding blijft

**Comment by jhore** [comment]
net in settings.php de variabele aangemaakt en melding weg. Overigens werkt bij mij de oplossing voor issue 32 nog niet overigens.

**Comment by Egregius** [comment]
Ja, die 0 he...
Anyway, deze settings mogen er al uit. Zit in de sensorstabel vanaf v20150207.

**Comment by jhore** [comment]
Na de update van bestanden, en database update  naar v20150207 de volgende foutmeldingen:
There was an error running the query [Unknown column 'tempk' in 'field list'] in setting screen onder bewerk sensors.

En in de home:
There was an error running the query [Unknown column 'correctie' in 'field list']

**Comment by Egregius** [comment]
Merde, de laatste versie van update.php was nog niet geupload. 
Als er in de footer al 20150207 staat ga je dat record moeten wissen uit de versie tabel om het script opnieuw te kunnen uitvoeren.

**Comment by jhore** [comment]
Geen probleem, gaan we proberen.

**Comment by jhore** [comment]
Hersteld. Settings page zet nu alleen altijd de invulvelden onder het menu, ipv ernaast. Top toevoeging de opmaak in settings menu.

**Comment by Egregius** [comment]
Probeer eens om css_body en/of css_item leeg te maken.

**Comment by jhore** [comment]
beide leeglaten resulteert weer in de "oude" layout.

**Comment by Egregius** [comment]
Da's dan goed. Is de bedoeling dat je daarmee custom css kan laden maar is redelijk tricky voor het responsive design.
