### ISSUE TITLE
Lichtsensor

### ISSUE THREAD

**Issue by jhore** [Egregius/HomewizardPHP#35]
Valt me nu pas op dat ik de lichtsensor niet terug ziet in de hoofdpage.

{"id":1,"name":"Lichtsensor","status":"no","type":"light","favorite":"no","timestamp":"08:11","cameraid":null}

**Comment by Egregius** [comment]
staat dit onder sensors?

Mvg,

Guy Verschuere
http://egregius.be

2015-02-12 14:36 GMT+01:00 jhore <notifications@github.com>:

**Comment by jhore** [comment]
Correct

**Comment by Egregius** [comment]
Toegevoegd in v20150212.

**Comment by jhore** [comment]
Super !
