### ISSUE TITLE
labels bij somfy schakelingen

### ISSUE THREAD

**Issue by DrakeNL** [Egregius/HomewizardPHP#5]
het zou wel makkelijk zijn als er labels voor de Somfy schakelingen zouden staan

**Comment by Egregius** [comment]
Wat bedoel je met labels? Staat de naam er dan niet naast?

**Comment by DrakeNL** [comment]
inderdaad de naam staat er niet naast. zie http://paltol.nl/wp-content/uploads/2015/01/somfy.jpg

**Comment by Egregius** [comment]
Heb je al update switches gedaan?

**Comment by DrakeNL** [comment]
De data stond al wel in de database. Na een update nog niet beschikbaar

**Comment by Egregius** [comment]
Zeker dat je alle files vervangen hebt, alsook de css etc? 
Een refresh gedaan in de browser? 
Tenzij dit ook komt door https://github.com/Egregius/HomewizardPHP/issues/3

**Comment by Egregius** [comment]
Should be fixed in 20150110
